{
  imports = [
    ./boot.nix
    ./nix.nix
    ./keyboard.nix
    ./outputs.nix
    ./substituters.nix
    ./nixpkgs.nix
    ./fish.nix
    ./users.nix
    ./home.nix
    ./loginscreen.nix
    ./locale.nix
    ./fonts.nix
    ./xdg.nix
    ./blockfile.nix
    ./common.nix
    ./steam.nix
  ];
}
