format = """
$os\
[](fg:#282a36 bg:#394260)\
$directory\
[](fg:#394260 bg:#bd93f9)\
$git_branch\
$git_status\
[](fg:#bd93f9 bg:#282a36)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#282a36 bg:#44475a)\
$time\
[ ](fg:#44475a)\
$shell\
$status\
$cmd_duration\
$username\
$hostname\
$localip\
"""



[os]
disabled = false
style =  "bg:#282a36 fg:#bd93f9"
format = "[$symbol]($style)"

[os.symbols]
EndeavourOS = "  "

[username]
disabled = false

[directory]
style = "fg:#bd93f9 bg:#394260"
format = '[ $path ]($style)'
before_repo_root_style = "fg:#bd93f9 bg:#394260"
repo_root_style = "fg:#bd93f9 bg:#394260"
repo_root_format ="[$before_root_path ]($before_repo_root_style)[ $repo_root]($repo_root_style)[$path]($style)"

[directory.substitutions]
"GitHub" = ""
"repos" = ""
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#bd93f9"
format = '[[ $symbol $branch ](fg:#394260 bg:#bd93f9)]($style)'

[git_status]
style = "bg:#bd93f9"
format = '[[($all_status$ahead_behind )](fg:#394260 bg:#bd93f9)]($style)'

[nodejs]
symbol = ""
style = "bg:#282a36"
format = '[[ $symbol ($version) ](fg:#59fa7b bg:#282a36)]($style)'

[rust]
symbol = ""
style = "bg:#282a36"
format = '[[ $symbol ($version) ](fg:#ffb86c bg:#282a36)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#282a36"
format = '[[ $symbol ($version) ](fg:#8be9fd bg:#282a36)]($style)'

[php]
symbol = ""
style = "bg:#282a36"
format = '[[ $symbol ($version) ](fg:#6272a4 bg:#282a36)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6272a4"
format = '[[  $time ](fg:#bd93f9 bg:#44475a)]($style)'

[character]
error_symbol = "[](bold #ff5555)"
success_symbol = "[](bold #50fa7b)"
